package com.micro.web.dao.impl;

import com.micro.web.dao.EssayDAO;
import com.micro.web.entities.Essay;
import com.micro.web.entities.EssayExample;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class EssayDAOImpl extends BaseDao implements EssayDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table essay
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public EssayDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table essay
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public void insert(Essay record) {
        getSqlMapClientTemplate().insert("essay.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table essay
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public List selectByExample(EssayExample example, String orderByClause) {
        Map parms = getExampleParms(example);
        if (orderByClause != null) {
            parms.put("ABATOR_ORDER_BY_CLAUSE", orderByClause);
        }
        List list = getSqlMapClientTemplate().queryForList("essay.abatorgenerated_selectByExample", parms);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table essay
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public List selectByExample(EssayExample example) {
        return selectByExample(example, null);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table essay
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public int deleteByExample(EssayExample example) {
        int rows = getSqlMapClientTemplate().delete("essay.abatorgenerated_deleteByExample", getExampleParms(example));
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table essay
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    private Map getessayIdExampleParms(EssayExample example) {
        Map parms = new HashMap();
        switch (example.getEssayid_Indicator()) {
        case EssayExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_essayId_NULL", "Y");
            } else {
                parms.put("AND_essayId_NULL", "Y");
            }
            break;
        case EssayExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_essayId_NOT_NULL", "Y");
            } else {
                parms.put("AND_essayId_NOT_NULL", "Y");
            }
            break;
        case EssayExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_essayId_EQUALS", "Y");
            } else {
                parms.put("AND_essayId_EQUALS", "Y");
            }
            parms.put("essayid", example.getEssayid());
            break;
        case EssayExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_essayId_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_essayId_NOT_EQUALS", "Y");
            }
            parms.put("essayid", example.getEssayid());
            break;
        case EssayExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_essayId_GT", "Y");
            } else {
                parms.put("AND_essayId_GT", "Y");
            }
            parms.put("essayid", example.getEssayid());
            break;
        case EssayExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_essayId_GE", "Y");
            } else {
                parms.put("AND_essayId_GE", "Y");
            }
            parms.put("essayid", example.getEssayid());
            break;
        case EssayExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_essayId_LT", "Y");
            } else {
                parms.put("AND_essayId_LT", "Y");
            }
            parms.put("essayid", example.getEssayid());
            break;
        case EssayExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_essayId_LE", "Y");
            } else {
                parms.put("AND_essayId_LE", "Y");
            }
            parms.put("essayid", example.getEssayid());
            break;
        case EssayExample.EXAMPLE_LIKE:
            if (example.isCombineTypeOr()) {
                parms.put("OR_essayId_LIKE", "Y");
            } else {
                parms.put("AND_essayId_LIKE", "Y");
            }
            parms.put("essayid", example.getEssayid());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table essay
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    private Map gettittleExampleParms(EssayExample example) {
        Map parms = new HashMap();
        switch (example.getTittle_Indicator()) {
        case EssayExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_tittle_NULL", "Y");
            } else {
                parms.put("AND_tittle_NULL", "Y");
            }
            break;
        case EssayExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_tittle_NOT_NULL", "Y");
            } else {
                parms.put("AND_tittle_NOT_NULL", "Y");
            }
            break;
        case EssayExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_tittle_EQUALS", "Y");
            } else {
                parms.put("AND_tittle_EQUALS", "Y");
            }
            parms.put("tittle", example.getTittle());
            break;
        case EssayExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_tittle_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_tittle_NOT_EQUALS", "Y");
            }
            parms.put("tittle", example.getTittle());
            break;
        case EssayExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_tittle_GT", "Y");
            } else {
                parms.put("AND_tittle_GT", "Y");
            }
            parms.put("tittle", example.getTittle());
            break;
        case EssayExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_tittle_GE", "Y");
            } else {
                parms.put("AND_tittle_GE", "Y");
            }
            parms.put("tittle", example.getTittle());
            break;
        case EssayExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_tittle_LT", "Y");
            } else {
                parms.put("AND_tittle_LT", "Y");
            }
            parms.put("tittle", example.getTittle());
            break;
        case EssayExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_tittle_LE", "Y");
            } else {
                parms.put("AND_tittle_LE", "Y");
            }
            parms.put("tittle", example.getTittle());
            break;
        case EssayExample.EXAMPLE_LIKE:
            if (example.isCombineTypeOr()) {
                parms.put("OR_tittle_LIKE", "Y");
            } else {
                parms.put("AND_tittle_LIKE", "Y");
            }
            parms.put("tittle", example.getTittle());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table essay
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    private Map getvisit_timesExampleParms(EssayExample example) {
        Map parms = new HashMap();
        switch (example.getVisitTimes_Indicator()) {
        case EssayExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_visit_times_NULL", "Y");
            } else {
                parms.put("AND_visit_times_NULL", "Y");
            }
            break;
        case EssayExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_visit_times_NOT_NULL", "Y");
            } else {
                parms.put("AND_visit_times_NOT_NULL", "Y");
            }
            break;
        case EssayExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_visit_times_EQUALS", "Y");
            } else {
                parms.put("AND_visit_times_EQUALS", "Y");
            }
            parms.put("visitTimes", example.getVisitTimes());
            break;
        case EssayExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_visit_times_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_visit_times_NOT_EQUALS", "Y");
            }
            parms.put("visitTimes", example.getVisitTimes());
            break;
        case EssayExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_visit_times_GT", "Y");
            } else {
                parms.put("AND_visit_times_GT", "Y");
            }
            parms.put("visitTimes", example.getVisitTimes());
            break;
        case EssayExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_visit_times_GE", "Y");
            } else {
                parms.put("AND_visit_times_GE", "Y");
            }
            parms.put("visitTimes", example.getVisitTimes());
            break;
        case EssayExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_visit_times_LT", "Y");
            } else {
                parms.put("AND_visit_times_LT", "Y");
            }
            parms.put("visitTimes", example.getVisitTimes());
            break;
        case EssayExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_visit_times_LE", "Y");
            } else {
                parms.put("AND_visit_times_LE", "Y");
            }
            parms.put("visitTimes", example.getVisitTimes());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table essay
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    private Map getreputation_goodExampleParms(EssayExample example) {
        Map parms = new HashMap();
        switch (example.getReputationGood_Indicator()) {
        case EssayExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_reputation_good_NULL", "Y");
            } else {
                parms.put("AND_reputation_good_NULL", "Y");
            }
            break;
        case EssayExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_reputation_good_NOT_NULL", "Y");
            } else {
                parms.put("AND_reputation_good_NOT_NULL", "Y");
            }
            break;
        case EssayExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_reputation_good_EQUALS", "Y");
            } else {
                parms.put("AND_reputation_good_EQUALS", "Y");
            }
            parms.put("reputationGood", example.getReputationGood());
            break;
        case EssayExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_reputation_good_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_reputation_good_NOT_EQUALS", "Y");
            }
            parms.put("reputationGood", example.getReputationGood());
            break;
        case EssayExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_reputation_good_GT", "Y");
            } else {
                parms.put("AND_reputation_good_GT", "Y");
            }
            parms.put("reputationGood", example.getReputationGood());
            break;
        case EssayExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_reputation_good_GE", "Y");
            } else {
                parms.put("AND_reputation_good_GE", "Y");
            }
            parms.put("reputationGood", example.getReputationGood());
            break;
        case EssayExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_reputation_good_LT", "Y");
            } else {
                parms.put("AND_reputation_good_LT", "Y");
            }
            parms.put("reputationGood", example.getReputationGood());
            break;
        case EssayExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_reputation_good_LE", "Y");
            } else {
                parms.put("AND_reputation_good_LE", "Y");
            }
            parms.put("reputationGood", example.getReputationGood());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table essay
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    private Map getreputation_badExampleParms(EssayExample example) {
        Map parms = new HashMap();
        switch (example.getReputationBad_Indicator()) {
        case EssayExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_reputation_bad_NULL", "Y");
            } else {
                parms.put("AND_reputation_bad_NULL", "Y");
            }
            break;
        case EssayExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_reputation_bad_NOT_NULL", "Y");
            } else {
                parms.put("AND_reputation_bad_NOT_NULL", "Y");
            }
            break;
        case EssayExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_reputation_bad_EQUALS", "Y");
            } else {
                parms.put("AND_reputation_bad_EQUALS", "Y");
            }
            parms.put("reputationBad", example.getReputationBad());
            break;
        case EssayExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_reputation_bad_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_reputation_bad_NOT_EQUALS", "Y");
            }
            parms.put("reputationBad", example.getReputationBad());
            break;
        case EssayExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_reputation_bad_GT", "Y");
            } else {
                parms.put("AND_reputation_bad_GT", "Y");
            }
            parms.put("reputationBad", example.getReputationBad());
            break;
        case EssayExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_reputation_bad_GE", "Y");
            } else {
                parms.put("AND_reputation_bad_GE", "Y");
            }
            parms.put("reputationBad", example.getReputationBad());
            break;
        case EssayExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_reputation_bad_LT", "Y");
            } else {
                parms.put("AND_reputation_bad_LT", "Y");
            }
            parms.put("reputationBad", example.getReputationBad());
            break;
        case EssayExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_reputation_bad_LE", "Y");
            } else {
                parms.put("AND_reputation_bad_LE", "Y");
            }
            parms.put("reputationBad", example.getReputationBad());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table essay
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    private Map getpictureExampleParms(EssayExample example) {
        Map parms = new HashMap();
        switch (example.getPicture_Indicator()) {
        case EssayExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_picture_NULL", "Y");
            } else {
                parms.put("AND_picture_NULL", "Y");
            }
            break;
        case EssayExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_picture_NOT_NULL", "Y");
            } else {
                parms.put("AND_picture_NOT_NULL", "Y");
            }
            break;
        case EssayExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_picture_EQUALS", "Y");
            } else {
                parms.put("AND_picture_EQUALS", "Y");
            }
            parms.put("picture", example.getPicture());
            break;
        case EssayExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_picture_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_picture_NOT_EQUALS", "Y");
            }
            parms.put("picture", example.getPicture());
            break;
        case EssayExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_picture_GT", "Y");
            } else {
                parms.put("AND_picture_GT", "Y");
            }
            parms.put("picture", example.getPicture());
            break;
        case EssayExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_picture_GE", "Y");
            } else {
                parms.put("AND_picture_GE", "Y");
            }
            parms.put("picture", example.getPicture());
            break;
        case EssayExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_picture_LT", "Y");
            } else {
                parms.put("AND_picture_LT", "Y");
            }
            parms.put("picture", example.getPicture());
            break;
        case EssayExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_picture_LE", "Y");
            } else {
                parms.put("AND_picture_LE", "Y");
            }
            parms.put("picture", example.getPicture());
            break;
        case EssayExample.EXAMPLE_LIKE:
            if (example.isCombineTypeOr()) {
                parms.put("OR_picture_LIKE", "Y");
            } else {
                parms.put("AND_picture_LIKE", "Y");
            }
            parms.put("picture", example.getPicture());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table essay
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    private Map getpathExampleParms(EssayExample example) {
        Map parms = new HashMap();
        switch (example.getPath_Indicator()) {
        case EssayExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_path_NULL", "Y");
            } else {
                parms.put("AND_path_NULL", "Y");
            }
            break;
        case EssayExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_path_NOT_NULL", "Y");
            } else {
                parms.put("AND_path_NOT_NULL", "Y");
            }
            break;
        case EssayExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_path_EQUALS", "Y");
            } else {
                parms.put("AND_path_EQUALS", "Y");
            }
            parms.put("path", example.getPath());
            break;
        case EssayExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_path_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_path_NOT_EQUALS", "Y");
            }
            parms.put("path", example.getPath());
            break;
        case EssayExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_path_GT", "Y");
            } else {
                parms.put("AND_path_GT", "Y");
            }
            parms.put("path", example.getPath());
            break;
        case EssayExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_path_GE", "Y");
            } else {
                parms.put("AND_path_GE", "Y");
            }
            parms.put("path", example.getPath());
            break;
        case EssayExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_path_LT", "Y");
            } else {
                parms.put("AND_path_LT", "Y");
            }
            parms.put("path", example.getPath());
            break;
        case EssayExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_path_LE", "Y");
            } else {
                parms.put("AND_path_LE", "Y");
            }
            parms.put("path", example.getPath());
            break;
        case EssayExample.EXAMPLE_LIKE:
            if (example.isCombineTypeOr()) {
                parms.put("OR_path_LIKE", "Y");
            } else {
                parms.put("AND_path_LIKE", "Y");
            }
            parms.put("path", example.getPath());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table essay
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    private Map getregisterTimeExampleParms(EssayExample example) {
        Map parms = new HashMap();
        switch (example.getRegistertime_Indicator()) {
        case EssayExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_registerTime_NULL", "Y");
            } else {
                parms.put("AND_registerTime_NULL", "Y");
            }
            break;
        case EssayExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_registerTime_NOT_NULL", "Y");
            } else {
                parms.put("AND_registerTime_NOT_NULL", "Y");
            }
            break;
        case EssayExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_registerTime_EQUALS", "Y");
            } else {
                parms.put("AND_registerTime_EQUALS", "Y");
            }
            parms.put("registertime", example.getRegistertime());
            break;
        case EssayExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_registerTime_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_registerTime_NOT_EQUALS", "Y");
            }
            parms.put("registertime", example.getRegistertime());
            break;
        case EssayExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_registerTime_GT", "Y");
            } else {
                parms.put("AND_registerTime_GT", "Y");
            }
            parms.put("registertime", example.getRegistertime());
            break;
        case EssayExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_registerTime_GE", "Y");
            } else {
                parms.put("AND_registerTime_GE", "Y");
            }
            parms.put("registertime", example.getRegistertime());
            break;
        case EssayExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_registerTime_LT", "Y");
            } else {
                parms.put("AND_registerTime_LT", "Y");
            }
            parms.put("registertime", example.getRegistertime());
            break;
        case EssayExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_registerTime_LE", "Y");
            } else {
                parms.put("AND_registerTime_LE", "Y");
            }
            parms.put("registertime", example.getRegistertime());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table essay
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    private Map getExampleParms(EssayExample example) {
        Map parms = new HashMap();
        parms.putAll(getessayIdExampleParms(example));
        parms.putAll(gettittleExampleParms(example));
        parms.putAll(getvisit_timesExampleParms(example));
        parms.putAll(getreputation_goodExampleParms(example));
        parms.putAll(getreputation_badExampleParms(example));
        parms.putAll(getpictureExampleParms(example));
        parms.putAll(getpathExampleParms(example));
        parms.putAll(getregisterTimeExampleParms(example));
        return parms;
    }
}