package com.micro.web.dao.impl;

import com.micro.web.dao.UserDAO;
import com.micro.web.entities.User;
import com.micro.web.entities.UserExample;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class UserDAOImpl extends BaseDao implements UserDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public UserDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public void insert(User record) {
        getSqlMapClientTemplate().insert("user.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public int updateByPrimaryKey(User record) {
        int rows = getSqlMapClientTemplate().update("user.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public int updateByPrimaryKeySelective(User record) {
        int rows = getSqlMapClientTemplate().update("user.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public List selectByExample(UserExample example, String orderByClause) {
        Map parms = getExampleParms(example);
        if (orderByClause != null) {
            parms.put("ABATOR_ORDER_BY_CLAUSE", orderByClause);
        }
        List list = getSqlMapClientTemplate().queryForList("user.abatorgenerated_selectByExample", parms);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public List selectByExample(UserExample example) {
        return selectByExample(example, null);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public User selectByPrimaryKey(String userid) {
        User key = new User();
        key.setUserid(userid);
        User record = (User) getSqlMapClientTemplate().queryForObject("user.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public int deleteByExample(UserExample example) {
        int rows = getSqlMapClientTemplate().delete("user.abatorgenerated_deleteByExample", getExampleParms(example));
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public int deleteByPrimaryKey(String userid) {
        User key = new User();
        key.setUserid(userid);
        int rows = getSqlMapClientTemplate().delete("user.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    private Map getuserIdExampleParms(UserExample example) {
        Map parms = new HashMap();
        switch (example.getUserid_Indicator()) {
        case UserExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_userId_NULL", "Y");
            } else {
                parms.put("AND_userId_NULL", "Y");
            }
            break;
        case UserExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_userId_NOT_NULL", "Y");
            } else {
                parms.put("AND_userId_NOT_NULL", "Y");
            }
            break;
        case UserExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_userId_EQUALS", "Y");
            } else {
                parms.put("AND_userId_EQUALS", "Y");
            }
            parms.put("userid", example.getUserid());
            break;
        case UserExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_userId_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_userId_NOT_EQUALS", "Y");
            }
            parms.put("userid", example.getUserid());
            break;
        case UserExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_userId_GT", "Y");
            } else {
                parms.put("AND_userId_GT", "Y");
            }
            parms.put("userid", example.getUserid());
            break;
        case UserExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_userId_GE", "Y");
            } else {
                parms.put("AND_userId_GE", "Y");
            }
            parms.put("userid", example.getUserid());
            break;
        case UserExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_userId_LT", "Y");
            } else {
                parms.put("AND_userId_LT", "Y");
            }
            parms.put("userid", example.getUserid());
            break;
        case UserExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_userId_LE", "Y");
            } else {
                parms.put("AND_userId_LE", "Y");
            }
            parms.put("userid", example.getUserid());
            break;
        case UserExample.EXAMPLE_LIKE:
            if (example.isCombineTypeOr()) {
                parms.put("OR_userId_LIKE", "Y");
            } else {
                parms.put("AND_userId_LIKE", "Y");
            }
            parms.put("userid", example.getUserid());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    private Map getphoneExampleParms(UserExample example) {
        Map parms = new HashMap();
        switch (example.getPhone_Indicator()) {
        case UserExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_phone_NULL", "Y");
            } else {
                parms.put("AND_phone_NULL", "Y");
            }
            break;
        case UserExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_phone_NOT_NULL", "Y");
            } else {
                parms.put("AND_phone_NOT_NULL", "Y");
            }
            break;
        case UserExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_phone_EQUALS", "Y");
            } else {
                parms.put("AND_phone_EQUALS", "Y");
            }
            parms.put("phone", example.getPhone());
            break;
        case UserExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_phone_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_phone_NOT_EQUALS", "Y");
            }
            parms.put("phone", example.getPhone());
            break;
        case UserExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_phone_GT", "Y");
            } else {
                parms.put("AND_phone_GT", "Y");
            }
            parms.put("phone", example.getPhone());
            break;
        case UserExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_phone_GE", "Y");
            } else {
                parms.put("AND_phone_GE", "Y");
            }
            parms.put("phone", example.getPhone());
            break;
        case UserExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_phone_LT", "Y");
            } else {
                parms.put("AND_phone_LT", "Y");
            }
            parms.put("phone", example.getPhone());
            break;
        case UserExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_phone_LE", "Y");
            } else {
                parms.put("AND_phone_LE", "Y");
            }
            parms.put("phone", example.getPhone());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    private Map getnameExampleParms(UserExample example) {
        Map parms = new HashMap();
        switch (example.getName_Indicator()) {
        case UserExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_name_NULL", "Y");
            } else {
                parms.put("AND_name_NULL", "Y");
            }
            break;
        case UserExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_name_NOT_NULL", "Y");
            } else {
                parms.put("AND_name_NOT_NULL", "Y");
            }
            break;
        case UserExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_name_EQUALS", "Y");
            } else {
                parms.put("AND_name_EQUALS", "Y");
            }
            parms.put("name", example.getName());
            break;
        case UserExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_name_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_name_NOT_EQUALS", "Y");
            }
            parms.put("name", example.getName());
            break;
        case UserExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_name_GT", "Y");
            } else {
                parms.put("AND_name_GT", "Y");
            }
            parms.put("name", example.getName());
            break;
        case UserExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_name_GE", "Y");
            } else {
                parms.put("AND_name_GE", "Y");
            }
            parms.put("name", example.getName());
            break;
        case UserExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_name_LT", "Y");
            } else {
                parms.put("AND_name_LT", "Y");
            }
            parms.put("name", example.getName());
            break;
        case UserExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_name_LE", "Y");
            } else {
                parms.put("AND_name_LE", "Y");
            }
            parms.put("name", example.getName());
            break;
        case UserExample.EXAMPLE_LIKE:
            if (example.isCombineTypeOr()) {
                parms.put("OR_name_LIKE", "Y");
            } else {
                parms.put("AND_name_LIKE", "Y");
            }
            parms.put("name", example.getName());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    private Map getauthorityExampleParms(UserExample example) {
        Map parms = new HashMap();
        switch (example.getAuthority_Indicator()) {
        case UserExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_authority_NULL", "Y");
            } else {
                parms.put("AND_authority_NULL", "Y");
            }
            break;
        case UserExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_authority_NOT_NULL", "Y");
            } else {
                parms.put("AND_authority_NOT_NULL", "Y");
            }
            break;
        case UserExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_authority_EQUALS", "Y");
            } else {
                parms.put("AND_authority_EQUALS", "Y");
            }
            parms.put("authority", example.getAuthority());
            break;
        case UserExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_authority_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_authority_NOT_EQUALS", "Y");
            }
            parms.put("authority", example.getAuthority());
            break;
        case UserExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_authority_GT", "Y");
            } else {
                parms.put("AND_authority_GT", "Y");
            }
            parms.put("authority", example.getAuthority());
            break;
        case UserExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_authority_GE", "Y");
            } else {
                parms.put("AND_authority_GE", "Y");
            }
            parms.put("authority", example.getAuthority());
            break;
        case UserExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_authority_LT", "Y");
            } else {
                parms.put("AND_authority_LT", "Y");
            }
            parms.put("authority", example.getAuthority());
            break;
        case UserExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_authority_LE", "Y");
            } else {
                parms.put("AND_authority_LE", "Y");
            }
            parms.put("authority", example.getAuthority());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    private Map getusernameExampleParms(UserExample example) {
        Map parms = new HashMap();
        switch (example.getUsername_Indicator()) {
        case UserExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_username_NULL", "Y");
            } else {
                parms.put("AND_username_NULL", "Y");
            }
            break;
        case UserExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_username_NOT_NULL", "Y");
            } else {
                parms.put("AND_username_NOT_NULL", "Y");
            }
            break;
        case UserExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_username_EQUALS", "Y");
            } else {
                parms.put("AND_username_EQUALS", "Y");
            }
            parms.put("username", example.getUsername());
            break;
        case UserExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_username_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_username_NOT_EQUALS", "Y");
            }
            parms.put("username", example.getUsername());
            break;
        case UserExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_username_GT", "Y");
            } else {
                parms.put("AND_username_GT", "Y");
            }
            parms.put("username", example.getUsername());
            break;
        case UserExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_username_GE", "Y");
            } else {
                parms.put("AND_username_GE", "Y");
            }
            parms.put("username", example.getUsername());
            break;
        case UserExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_username_LT", "Y");
            } else {
                parms.put("AND_username_LT", "Y");
            }
            parms.put("username", example.getUsername());
            break;
        case UserExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_username_LE", "Y");
            } else {
                parms.put("AND_username_LE", "Y");
            }
            parms.put("username", example.getUsername());
            break;
        case UserExample.EXAMPLE_LIKE:
            if (example.isCombineTypeOr()) {
                parms.put("OR_username_LIKE", "Y");
            } else {
                parms.put("AND_username_LIKE", "Y");
            }
            parms.put("username", example.getUsername());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    private Map getpasswordExampleParms(UserExample example) {
        Map parms = new HashMap();
        switch (example.getPassword_Indicator()) {
        case UserExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_password_NULL", "Y");
            } else {
                parms.put("AND_password_NULL", "Y");
            }
            break;
        case UserExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_password_NOT_NULL", "Y");
            } else {
                parms.put("AND_password_NOT_NULL", "Y");
            }
            break;
        case UserExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_password_EQUALS", "Y");
            } else {
                parms.put("AND_password_EQUALS", "Y");
            }
            parms.put("password", example.getPassword());
            break;
        case UserExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_password_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_password_NOT_EQUALS", "Y");
            }
            parms.put("password", example.getPassword());
            break;
        case UserExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_password_GT", "Y");
            } else {
                parms.put("AND_password_GT", "Y");
            }
            parms.put("password", example.getPassword());
            break;
        case UserExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_password_GE", "Y");
            } else {
                parms.put("AND_password_GE", "Y");
            }
            parms.put("password", example.getPassword());
            break;
        case UserExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_password_LT", "Y");
            } else {
                parms.put("AND_password_LT", "Y");
            }
            parms.put("password", example.getPassword());
            break;
        case UserExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_password_LE", "Y");
            } else {
                parms.put("AND_password_LE", "Y");
            }
            parms.put("password", example.getPassword());
            break;
        case UserExample.EXAMPLE_LIKE:
            if (example.isCombineTypeOr()) {
                parms.put("OR_password_LIKE", "Y");
            } else {
                parms.put("AND_password_LIKE", "Y");
            }
            parms.put("password", example.getPassword());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    private Map getidcardExampleParms(UserExample example) {
        Map parms = new HashMap();
        switch (example.getIdcard_Indicator()) {
        case UserExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_idcard_NULL", "Y");
            } else {
                parms.put("AND_idcard_NULL", "Y");
            }
            break;
        case UserExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_idcard_NOT_NULL", "Y");
            } else {
                parms.put("AND_idcard_NOT_NULL", "Y");
            }
            break;
        case UserExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_idcard_EQUALS", "Y");
            } else {
                parms.put("AND_idcard_EQUALS", "Y");
            }
            parms.put("idcard", example.getIdcard());
            break;
        case UserExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_idcard_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_idcard_NOT_EQUALS", "Y");
            }
            parms.put("idcard", example.getIdcard());
            break;
        case UserExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_idcard_GT", "Y");
            } else {
                parms.put("AND_idcard_GT", "Y");
            }
            parms.put("idcard", example.getIdcard());
            break;
        case UserExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_idcard_GE", "Y");
            } else {
                parms.put("AND_idcard_GE", "Y");
            }
            parms.put("idcard", example.getIdcard());
            break;
        case UserExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_idcard_LT", "Y");
            } else {
                parms.put("AND_idcard_LT", "Y");
            }
            parms.put("idcard", example.getIdcard());
            break;
        case UserExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_idcard_LE", "Y");
            } else {
                parms.put("AND_idcard_LE", "Y");
            }
            parms.put("idcard", example.getIdcard());
            break;
        case UserExample.EXAMPLE_LIKE:
            if (example.isCombineTypeOr()) {
                parms.put("OR_idcard_LIKE", "Y");
            } else {
                parms.put("AND_idcard_LIKE", "Y");
            }
            parms.put("idcard", example.getIdcard());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    private Map getregisterTimeExampleParms(UserExample example) {
        Map parms = new HashMap();
        switch (example.getRegistertime_Indicator()) {
        case UserExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_registerTime_NULL", "Y");
            } else {
                parms.put("AND_registerTime_NULL", "Y");
            }
            break;
        case UserExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_registerTime_NOT_NULL", "Y");
            } else {
                parms.put("AND_registerTime_NOT_NULL", "Y");
            }
            break;
        case UserExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_registerTime_EQUALS", "Y");
            } else {
                parms.put("AND_registerTime_EQUALS", "Y");
            }
            parms.put("registertime", example.getRegistertime());
            break;
        case UserExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_registerTime_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_registerTime_NOT_EQUALS", "Y");
            }
            parms.put("registertime", example.getRegistertime());
            break;
        case UserExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_registerTime_GT", "Y");
            } else {
                parms.put("AND_registerTime_GT", "Y");
            }
            parms.put("registertime", example.getRegistertime());
            break;
        case UserExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_registerTime_GE", "Y");
            } else {
                parms.put("AND_registerTime_GE", "Y");
            }
            parms.put("registertime", example.getRegistertime());
            break;
        case UserExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_registerTime_LT", "Y");
            } else {
                parms.put("AND_registerTime_LT", "Y");
            }
            parms.put("registertime", example.getRegistertime());
            break;
        case UserExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_registerTime_LE", "Y");
            } else {
                parms.put("AND_registerTime_LE", "Y");
            }
            parms.put("registertime", example.getRegistertime());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    private Map getlastLoginExampleParms(UserExample example) {
        Map parms = new HashMap();
        switch (example.getLastlogin_Indicator()) {
        case UserExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_lastLogin_NULL", "Y");
            } else {
                parms.put("AND_lastLogin_NULL", "Y");
            }
            break;
        case UserExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_lastLogin_NOT_NULL", "Y");
            } else {
                parms.put("AND_lastLogin_NOT_NULL", "Y");
            }
            break;
        case UserExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_lastLogin_EQUALS", "Y");
            } else {
                parms.put("AND_lastLogin_EQUALS", "Y");
            }
            parms.put("lastlogin", example.getLastlogin());
            break;
        case UserExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_lastLogin_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_lastLogin_NOT_EQUALS", "Y");
            }
            parms.put("lastlogin", example.getLastlogin());
            break;
        case UserExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_lastLogin_GT", "Y");
            } else {
                parms.put("AND_lastLogin_GT", "Y");
            }
            parms.put("lastlogin", example.getLastlogin());
            break;
        case UserExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_lastLogin_GE", "Y");
            } else {
                parms.put("AND_lastLogin_GE", "Y");
            }
            parms.put("lastlogin", example.getLastlogin());
            break;
        case UserExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_lastLogin_LT", "Y");
            } else {
                parms.put("AND_lastLogin_LT", "Y");
            }
            parms.put("lastlogin", example.getLastlogin());
            break;
        case UserExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_lastLogin_LE", "Y");
            } else {
                parms.put("AND_lastLogin_LE", "Y");
            }
            parms.put("lastlogin", example.getLastlogin());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    private Map getExampleParms(UserExample example) {
        Map parms = new HashMap();
        parms.putAll(getuserIdExampleParms(example));
        parms.putAll(getphoneExampleParms(example));
        parms.putAll(getnameExampleParms(example));
        parms.putAll(getauthorityExampleParms(example));
        parms.putAll(getusernameExampleParms(example));
        parms.putAll(getpasswordExampleParms(example));
        parms.putAll(getidcardExampleParms(example));
        parms.putAll(getregisterTimeExampleParms(example));
        parms.putAll(getlastLoginExampleParms(example));
        return parms;
    }
}