package com.micro.web.dao.impl;

import com.micro.web.dao.VideocommentsDAO;
import com.micro.web.entities.Videocomments;
import com.micro.web.entities.VideocommentsExample;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class VideocommentsDAOImpl extends BaseDao implements VideocommentsDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table videocomments
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public VideocommentsDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table videocomments
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public void insert(Videocomments record) {
        getSqlMapClientTemplate().insert("videocomments.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table videocomments
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public int updateByPrimaryKey(Videocomments record) {
        int rows = getSqlMapClientTemplate().update("videocomments.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table videocomments
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public int updateByPrimaryKeySelective(Videocomments record) {
        int rows = getSqlMapClientTemplate().update("videocomments.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table videocomments
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public List selectByExample(VideocommentsExample example, String orderByClause) {
        Map parms = getExampleParms(example);
        if (orderByClause != null) {
            parms.put("ABATOR_ORDER_BY_CLAUSE", orderByClause);
        }
        List list = getSqlMapClientTemplate().queryForList("videocomments.abatorgenerated_selectByExample", parms);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table videocomments
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public List selectByExample(VideocommentsExample example) {
        return selectByExample(example, null);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table videocomments
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public Videocomments selectByPrimaryKey(String videocommentsid) {
        Videocomments key = new Videocomments();
        key.setVideocommentsid(videocommentsid);
        Videocomments record = (Videocomments) getSqlMapClientTemplate().queryForObject("videocomments.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table videocomments
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public int deleteByExample(VideocommentsExample example) {
        int rows = getSqlMapClientTemplate().delete("videocomments.abatorgenerated_deleteByExample", getExampleParms(example));
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table videocomments
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public int deleteByPrimaryKey(String videocommentsid) {
        Videocomments key = new Videocomments();
        key.setVideocommentsid(videocommentsid);
        int rows = getSqlMapClientTemplate().delete("videocomments.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table videocomments
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    private Map getvideoCommentsIdExampleParms(VideocommentsExample example) {
        Map parms = new HashMap();
        switch (example.getVideocommentsid_Indicator()) {
        case VideocommentsExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_videoCommentsId_NULL", "Y");
            } else {
                parms.put("AND_videoCommentsId_NULL", "Y");
            }
            break;
        case VideocommentsExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_videoCommentsId_NOT_NULL", "Y");
            } else {
                parms.put("AND_videoCommentsId_NOT_NULL", "Y");
            }
            break;
        case VideocommentsExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_videoCommentsId_EQUALS", "Y");
            } else {
                parms.put("AND_videoCommentsId_EQUALS", "Y");
            }
            parms.put("videocommentsid", example.getVideocommentsid());
            break;
        case VideocommentsExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_videoCommentsId_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_videoCommentsId_NOT_EQUALS", "Y");
            }
            parms.put("videocommentsid", example.getVideocommentsid());
            break;
        case VideocommentsExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_videoCommentsId_GT", "Y");
            } else {
                parms.put("AND_videoCommentsId_GT", "Y");
            }
            parms.put("videocommentsid", example.getVideocommentsid());
            break;
        case VideocommentsExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_videoCommentsId_GE", "Y");
            } else {
                parms.put("AND_videoCommentsId_GE", "Y");
            }
            parms.put("videocommentsid", example.getVideocommentsid());
            break;
        case VideocommentsExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_videoCommentsId_LT", "Y");
            } else {
                parms.put("AND_videoCommentsId_LT", "Y");
            }
            parms.put("videocommentsid", example.getVideocommentsid());
            break;
        case VideocommentsExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_videoCommentsId_LE", "Y");
            } else {
                parms.put("AND_videoCommentsId_LE", "Y");
            }
            parms.put("videocommentsid", example.getVideocommentsid());
            break;
        case VideocommentsExample.EXAMPLE_LIKE:
            if (example.isCombineTypeOr()) {
                parms.put("OR_videoCommentsId_LIKE", "Y");
            } else {
                parms.put("AND_videoCommentsId_LIKE", "Y");
            }
            parms.put("videocommentsid", example.getVideocommentsid());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table videocomments
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    private Map getvideoIdExampleParms(VideocommentsExample example) {
        Map parms = new HashMap();
        switch (example.getVideoid_Indicator()) {
        case VideocommentsExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_videoId_NULL", "Y");
            } else {
                parms.put("AND_videoId_NULL", "Y");
            }
            break;
        case VideocommentsExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_videoId_NOT_NULL", "Y");
            } else {
                parms.put("AND_videoId_NOT_NULL", "Y");
            }
            break;
        case VideocommentsExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_videoId_EQUALS", "Y");
            } else {
                parms.put("AND_videoId_EQUALS", "Y");
            }
            parms.put("videoid", example.getVideoid());
            break;
        case VideocommentsExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_videoId_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_videoId_NOT_EQUALS", "Y");
            }
            parms.put("videoid", example.getVideoid());
            break;
        case VideocommentsExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_videoId_GT", "Y");
            } else {
                parms.put("AND_videoId_GT", "Y");
            }
            parms.put("videoid", example.getVideoid());
            break;
        case VideocommentsExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_videoId_GE", "Y");
            } else {
                parms.put("AND_videoId_GE", "Y");
            }
            parms.put("videoid", example.getVideoid());
            break;
        case VideocommentsExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_videoId_LT", "Y");
            } else {
                parms.put("AND_videoId_LT", "Y");
            }
            parms.put("videoid", example.getVideoid());
            break;
        case VideocommentsExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_videoId_LE", "Y");
            } else {
                parms.put("AND_videoId_LE", "Y");
            }
            parms.put("videoid", example.getVideoid());
            break;
        case VideocommentsExample.EXAMPLE_LIKE:
            if (example.isCombineTypeOr()) {
                parms.put("OR_videoId_LIKE", "Y");
            } else {
                parms.put("AND_videoId_LIKE", "Y");
            }
            parms.put("videoid", example.getVideoid());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table videocomments
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    private Map getuserIdExampleParms(VideocommentsExample example) {
        Map parms = new HashMap();
        switch (example.getUserid_Indicator()) {
        case VideocommentsExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_userId_NULL", "Y");
            } else {
                parms.put("AND_userId_NULL", "Y");
            }
            break;
        case VideocommentsExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_userId_NOT_NULL", "Y");
            } else {
                parms.put("AND_userId_NOT_NULL", "Y");
            }
            break;
        case VideocommentsExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_userId_EQUALS", "Y");
            } else {
                parms.put("AND_userId_EQUALS", "Y");
            }
            parms.put("userid", example.getUserid());
            break;
        case VideocommentsExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_userId_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_userId_NOT_EQUALS", "Y");
            }
            parms.put("userid", example.getUserid());
            break;
        case VideocommentsExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_userId_GT", "Y");
            } else {
                parms.put("AND_userId_GT", "Y");
            }
            parms.put("userid", example.getUserid());
            break;
        case VideocommentsExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_userId_GE", "Y");
            } else {
                parms.put("AND_userId_GE", "Y");
            }
            parms.put("userid", example.getUserid());
            break;
        case VideocommentsExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_userId_LT", "Y");
            } else {
                parms.put("AND_userId_LT", "Y");
            }
            parms.put("userid", example.getUserid());
            break;
        case VideocommentsExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_userId_LE", "Y");
            } else {
                parms.put("AND_userId_LE", "Y");
            }
            parms.put("userid", example.getUserid());
            break;
        case VideocommentsExample.EXAMPLE_LIKE:
            if (example.isCombineTypeOr()) {
                parms.put("OR_userId_LIKE", "Y");
            } else {
                parms.put("AND_userId_LIKE", "Y");
            }
            parms.put("userid", example.getUserid());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table videocomments
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    private Map getvideoComments_videoIdExampleParms(VideocommentsExample example) {
        Map parms = new HashMap();
        switch (example.getVideocommentsVideoid_Indicator()) {
        case VideocommentsExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_videoComments_videoId_NULL", "Y");
            } else {
                parms.put("AND_videoComments_videoId_NULL", "Y");
            }
            break;
        case VideocommentsExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_videoComments_videoId_NOT_NULL", "Y");
            } else {
                parms.put("AND_videoComments_videoId_NOT_NULL", "Y");
            }
            break;
        case VideocommentsExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_videoComments_videoId_EQUALS", "Y");
            } else {
                parms.put("AND_videoComments_videoId_EQUALS", "Y");
            }
            parms.put("videocommentsVideoid", example.getVideocommentsVideoid());
            break;
        case VideocommentsExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_videoComments_videoId_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_videoComments_videoId_NOT_EQUALS", "Y");
            }
            parms.put("videocommentsVideoid", example.getVideocommentsVideoid());
            break;
        case VideocommentsExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_videoComments_videoId_GT", "Y");
            } else {
                parms.put("AND_videoComments_videoId_GT", "Y");
            }
            parms.put("videocommentsVideoid", example.getVideocommentsVideoid());
            break;
        case VideocommentsExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_videoComments_videoId_GE", "Y");
            } else {
                parms.put("AND_videoComments_videoId_GE", "Y");
            }
            parms.put("videocommentsVideoid", example.getVideocommentsVideoid());
            break;
        case VideocommentsExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_videoComments_videoId_LT", "Y");
            } else {
                parms.put("AND_videoComments_videoId_LT", "Y");
            }
            parms.put("videocommentsVideoid", example.getVideocommentsVideoid());
            break;
        case VideocommentsExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_videoComments_videoId_LE", "Y");
            } else {
                parms.put("AND_videoComments_videoId_LE", "Y");
            }
            parms.put("videocommentsVideoid", example.getVideocommentsVideoid());
            break;
        case VideocommentsExample.EXAMPLE_LIKE:
            if (example.isCombineTypeOr()) {
                parms.put("OR_videoComments_videoId_LIKE", "Y");
            } else {
                parms.put("AND_videoComments_videoId_LIKE", "Y");
            }
            parms.put("videocommentsVideoid", example.getVideocommentsVideoid());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table videocomments
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    private Map getvideoComments_userIdExampleParms(VideocommentsExample example) {
        Map parms = new HashMap();
        switch (example.getVideocommentsUserid_Indicator()) {
        case VideocommentsExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_videoComments_userId_NULL", "Y");
            } else {
                parms.put("AND_videoComments_userId_NULL", "Y");
            }
            break;
        case VideocommentsExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_videoComments_userId_NOT_NULL", "Y");
            } else {
                parms.put("AND_videoComments_userId_NOT_NULL", "Y");
            }
            break;
        case VideocommentsExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_videoComments_userId_EQUALS", "Y");
            } else {
                parms.put("AND_videoComments_userId_EQUALS", "Y");
            }
            parms.put("videocommentsUserid", example.getVideocommentsUserid());
            break;
        case VideocommentsExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_videoComments_userId_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_videoComments_userId_NOT_EQUALS", "Y");
            }
            parms.put("videocommentsUserid", example.getVideocommentsUserid());
            break;
        case VideocommentsExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_videoComments_userId_GT", "Y");
            } else {
                parms.put("AND_videoComments_userId_GT", "Y");
            }
            parms.put("videocommentsUserid", example.getVideocommentsUserid());
            break;
        case VideocommentsExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_videoComments_userId_GE", "Y");
            } else {
                parms.put("AND_videoComments_userId_GE", "Y");
            }
            parms.put("videocommentsUserid", example.getVideocommentsUserid());
            break;
        case VideocommentsExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_videoComments_userId_LT", "Y");
            } else {
                parms.put("AND_videoComments_userId_LT", "Y");
            }
            parms.put("videocommentsUserid", example.getVideocommentsUserid());
            break;
        case VideocommentsExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_videoComments_userId_LE", "Y");
            } else {
                parms.put("AND_videoComments_userId_LE", "Y");
            }
            parms.put("videocommentsUserid", example.getVideocommentsUserid());
            break;
        case VideocommentsExample.EXAMPLE_LIKE:
            if (example.isCombineTypeOr()) {
                parms.put("OR_videoComments_userId_LIKE", "Y");
            } else {
                parms.put("AND_videoComments_userId_LIKE", "Y");
            }
            parms.put("videocommentsUserid", example.getVideocommentsUserid());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table videocomments
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    private Map getcontentExampleParms(VideocommentsExample example) {
        Map parms = new HashMap();
        switch (example.getContent_Indicator()) {
        case VideocommentsExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_content_NULL", "Y");
            } else {
                parms.put("AND_content_NULL", "Y");
            }
            break;
        case VideocommentsExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_content_NOT_NULL", "Y");
            } else {
                parms.put("AND_content_NOT_NULL", "Y");
            }
            break;
        case VideocommentsExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_content_EQUALS", "Y");
            } else {
                parms.put("AND_content_EQUALS", "Y");
            }
            parms.put("content", example.getContent());
            break;
        case VideocommentsExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_content_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_content_NOT_EQUALS", "Y");
            }
            parms.put("content", example.getContent());
            break;
        case VideocommentsExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_content_GT", "Y");
            } else {
                parms.put("AND_content_GT", "Y");
            }
            parms.put("content", example.getContent());
            break;
        case VideocommentsExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_content_GE", "Y");
            } else {
                parms.put("AND_content_GE", "Y");
            }
            parms.put("content", example.getContent());
            break;
        case VideocommentsExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_content_LT", "Y");
            } else {
                parms.put("AND_content_LT", "Y");
            }
            parms.put("content", example.getContent());
            break;
        case VideocommentsExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_content_LE", "Y");
            } else {
                parms.put("AND_content_LE", "Y");
            }
            parms.put("content", example.getContent());
            break;
        case VideocommentsExample.EXAMPLE_LIKE:
            if (example.isCombineTypeOr()) {
                parms.put("OR_content_LIKE", "Y");
            } else {
                parms.put("AND_content_LIKE", "Y");
            }
            parms.put("content", example.getContent());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table videocomments
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    private Map getregisterTimeExampleParms(VideocommentsExample example) {
        Map parms = new HashMap();
        switch (example.getRegistertime_Indicator()) {
        case VideocommentsExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_registerTime_NULL", "Y");
            } else {
                parms.put("AND_registerTime_NULL", "Y");
            }
            break;
        case VideocommentsExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_registerTime_NOT_NULL", "Y");
            } else {
                parms.put("AND_registerTime_NOT_NULL", "Y");
            }
            break;
        case VideocommentsExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_registerTime_EQUALS", "Y");
            } else {
                parms.put("AND_registerTime_EQUALS", "Y");
            }
            parms.put("registertime", example.getRegistertime());
            break;
        case VideocommentsExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_registerTime_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_registerTime_NOT_EQUALS", "Y");
            }
            parms.put("registertime", example.getRegistertime());
            break;
        case VideocommentsExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_registerTime_GT", "Y");
            } else {
                parms.put("AND_registerTime_GT", "Y");
            }
            parms.put("registertime", example.getRegistertime());
            break;
        case VideocommentsExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_registerTime_GE", "Y");
            } else {
                parms.put("AND_registerTime_GE", "Y");
            }
            parms.put("registertime", example.getRegistertime());
            break;
        case VideocommentsExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_registerTime_LT", "Y");
            } else {
                parms.put("AND_registerTime_LT", "Y");
            }
            parms.put("registertime", example.getRegistertime());
            break;
        case VideocommentsExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_registerTime_LE", "Y");
            } else {
                parms.put("AND_registerTime_LE", "Y");
            }
            parms.put("registertime", example.getRegistertime());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table videocomments
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    private Map getExampleParms(VideocommentsExample example) {
        Map parms = new HashMap();
        parms.putAll(getvideoCommentsIdExampleParms(example));
        parms.putAll(getvideoIdExampleParms(example));
        parms.putAll(getuserIdExampleParms(example));
        parms.putAll(getvideoComments_videoIdExampleParms(example));
        parms.putAll(getvideoComments_userIdExampleParms(example));
        parms.putAll(getcontentExampleParms(example));
        parms.putAll(getregisterTimeExampleParms(example));
        return parms;
    }
}