package com.micro.web.entities;

import java.util.Date;

public class Doctor {

    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column doctor.doctorid
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    private Long doctorid;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column doctor.loginname
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    private String loginname;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column doctor.password
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    private String password;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column doctor.sectionid
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    private Integer sectionid;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column doctor.groupid
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    private Integer groupid;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column doctor.doctorname
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    private String doctorname;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column doctor.idcard
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    private String idcard;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column doctor.doctormale
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    private Integer doctormale;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column doctor.birthday
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    private Date birthday;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column doctor.mobilephone
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    private String mobilephone;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column doctor.contactphone
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    private String contactphone;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column doctor.level
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    private Integer level;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column doctor.majardesc
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    private String majardesc;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column doctor.currentlogintime
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    private Date currentlogintime;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column doctor.latestlogintime
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    private Date latestlogintime;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column doctor.createuser
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    private Long createuser;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column doctor.createtime
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    private Date createtime;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column doctor.updateuser
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    private Long updateuser;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column doctor.updatetime
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    private Date updatetime;

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column doctor.doctorid
     * @return  the value of doctor.doctorid
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    public Long getDoctorid() {
	return doctorid;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column doctor.doctorid
     * @param doctorid  the value for doctor.doctorid
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    public void setDoctorid(Long doctorid) {
	this.doctorid = doctorid;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column doctor.loginname
     * @return  the value of doctor.loginname
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    public String getLoginname() {
	return loginname;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column doctor.loginname
     * @param loginname  the value for doctor.loginname
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    public void setLoginname(String loginname) {
	this.loginname = loginname;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column doctor.password
     * @return  the value of doctor.password
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    public String getPassword() {
	return password;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column doctor.password
     * @param password  the value for doctor.password
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    public void setPassword(String password) {
	this.password = password;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column doctor.sectionid
     * @return  the value of doctor.sectionid
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    public Integer getSectionid() {
	return sectionid;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column doctor.sectionid
     * @param sectionid  the value for doctor.sectionid
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    public void setSectionid(Integer sectionid) {
	this.sectionid = sectionid;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column doctor.groupid
     * @return  the value of doctor.groupid
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    public Integer getGroupid() {
	return groupid;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column doctor.groupid
     * @param groupid  the value for doctor.groupid
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    public void setGroupid(Integer groupid) {
	this.groupid = groupid;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column doctor.doctorname
     * @return  the value of doctor.doctorname
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    public String getDoctorname() {
	return doctorname;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column doctor.doctorname
     * @param doctorname  the value for doctor.doctorname
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    public void setDoctorname(String doctorname) {
	this.doctorname = doctorname;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column doctor.idcard
     * @return  the value of doctor.idcard
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    public String getIdcard() {
	return idcard;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column doctor.idcard
     * @param idcard  the value for doctor.idcard
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    public void setIdcard(String idcard) {
	this.idcard = idcard;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column doctor.doctormale
     * @return  the value of doctor.doctormale
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    public Integer getDoctormale() {
	return doctormale;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column doctor.doctormale
     * @param doctormale  the value for doctor.doctormale
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    public void setDoctormale(Integer doctormale) {
	this.doctormale = doctormale;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column doctor.birthday
     * @return  the value of doctor.birthday
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    public Date getBirthday() {
	return birthday;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column doctor.birthday
     * @param birthday  the value for doctor.birthday
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    public void setBirthday(Date birthday) {
	this.birthday = birthday;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column doctor.mobilephone
     * @return  the value of doctor.mobilephone
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    public String getMobilephone() {
	return mobilephone;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column doctor.mobilephone
     * @param mobilephone  the value for doctor.mobilephone
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    public void setMobilephone(String mobilephone) {
	this.mobilephone = mobilephone;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column doctor.contactphone
     * @return  the value of doctor.contactphone
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    public String getContactphone() {
	return contactphone;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column doctor.contactphone
     * @param contactphone  the value for doctor.contactphone
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    public void setContactphone(String contactphone) {
	this.contactphone = contactphone;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column doctor.level
     * @return  the value of doctor.level
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    public Integer getLevel() {
	return level;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column doctor.level
     * @param level  the value for doctor.level
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    public void setLevel(Integer level) {
	this.level = level;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column doctor.majardesc
     * @return  the value of doctor.majardesc
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    public String getMajardesc() {
	return majardesc;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column doctor.majardesc
     * @param majardesc  the value for doctor.majardesc
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    public void setMajardesc(String majardesc) {
	this.majardesc = majardesc;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column doctor.currentlogintime
     * @return  the value of doctor.currentlogintime
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    public Date getCurrentlogintime() {
	return currentlogintime;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column doctor.currentlogintime
     * @param currentlogintime  the value for doctor.currentlogintime
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    public void setCurrentlogintime(Date currentlogintime) {
	this.currentlogintime = currentlogintime;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column doctor.latestlogintime
     * @return  the value of doctor.latestlogintime
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    public Date getLatestlogintime() {
	return latestlogintime;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column doctor.latestlogintime
     * @param latestlogintime  the value for doctor.latestlogintime
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    public void setLatestlogintime(Date latestlogintime) {
	this.latestlogintime = latestlogintime;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column doctor.createuser
     * @return  the value of doctor.createuser
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    public Long getCreateuser() {
	return createuser;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column doctor.createuser
     * @param createuser  the value for doctor.createuser
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    public void setCreateuser(Long createuser) {
	this.createuser = createuser;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column doctor.createtime
     * @return  the value of doctor.createtime
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    public Date getCreatetime() {
	return createtime;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column doctor.createtime
     * @param createtime  the value for doctor.createtime
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    public void setCreatetime(Date createtime) {
	this.createtime = createtime;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column doctor.updateuser
     * @return  the value of doctor.updateuser
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    public Long getUpdateuser() {
	return updateuser;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column doctor.updateuser
     * @param updateuser  the value for doctor.updateuser
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    public void setUpdateuser(Long updateuser) {
	this.updateuser = updateuser;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column doctor.updatetime
     * @return  the value of doctor.updatetime
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    public Date getUpdatetime() {
	return updatetime;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column doctor.updatetime
     * @param updatetime  the value for doctor.updatetime
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    public void setUpdatetime(Date updatetime) {
	this.updatetime = updatetime;
    }
}