package com.micro.web.entities;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class DoctorExample extends Doctor {

    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table doctor
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    public static final int EXAMPLE_IGNORE = 0;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table doctor
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    public static final int EXAMPLE_NULL = 1;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table doctor
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    public static final int EXAMPLE_NOT_NULL = 2;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table doctor
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    public static final int EXAMPLE_EQUALS = 3;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table doctor
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    public static final int EXAMPLE_NOT_EQUALS = 4;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table doctor
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    public static final int EXAMPLE_GREATER_THAN = 5;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table doctor
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    public static final int EXAMPLE_GREATER_THAN_OR_EQUAL = 6;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table doctor
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    public static final int EXAMPLE_LESS_THAN = 7;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table doctor
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    public static final int EXAMPLE_LESS_THAN_OR_EQUAL = 8;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table doctor
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    public static final int EXAMPLE_LIKE = 9;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table doctor
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    private boolean combineTypeOr;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table doctor
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    private int doctorid_Indicator;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table doctor
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    private int loginname_Indicator;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table doctor
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    private int password_Indicator;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table doctor
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    private int sectionid_Indicator;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table doctor
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    private int groupid_Indicator;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table doctor
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    private int doctorname_Indicator;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table doctor
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    private int idcard_Indicator;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table doctor
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    private int doctormale_Indicator;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table doctor
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    private int birthday_Indicator;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table doctor
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    private int mobilephone_Indicator;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table doctor
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    private int contactphone_Indicator;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table doctor
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    private int level_Indicator;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table doctor
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    private int majardesc_Indicator;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table doctor
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    private int currentlogintime_Indicator;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table doctor
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    private int latestlogintime_Indicator;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table doctor
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    private int createuser_Indicator;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table doctor
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    private int createtime_Indicator;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table doctor
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    private int updateuser_Indicator;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table doctor
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    private int updatetime_Indicator;

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table doctor
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    public void setCombineTypeOr(boolean combineTypeOr) {
	this.combineTypeOr = combineTypeOr;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table doctor
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    public boolean isCombineTypeOr() {
	return combineTypeOr;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table doctor
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    public int getDoctorid_Indicator() {
	return doctorid_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table doctor
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    public void setDoctorid_Indicator(int doctorid_Indicator) {
	this.doctorid_Indicator = doctorid_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table doctor
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    public int getLoginname_Indicator() {
	return loginname_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table doctor
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    public void setLoginname_Indicator(int loginname_Indicator) {
	this.loginname_Indicator = loginname_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table doctor
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    public int getPassword_Indicator() {
	return password_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table doctor
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    public void setPassword_Indicator(int password_Indicator) {
	this.password_Indicator = password_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table doctor
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    public int getSectionid_Indicator() {
	return sectionid_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table doctor
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    public void setSectionid_Indicator(int sectionid_Indicator) {
	this.sectionid_Indicator = sectionid_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table doctor
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    public int getGroupid_Indicator() {
	return groupid_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table doctor
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    public void setGroupid_Indicator(int groupid_Indicator) {
	this.groupid_Indicator = groupid_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table doctor
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    public int getDoctorname_Indicator() {
	return doctorname_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table doctor
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    public void setDoctorname_Indicator(int doctorname_Indicator) {
	this.doctorname_Indicator = doctorname_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table doctor
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    public int getIdcard_Indicator() {
	return idcard_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table doctor
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    public void setIdcard_Indicator(int idcard_Indicator) {
	this.idcard_Indicator = idcard_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table doctor
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    public int getDoctormale_Indicator() {
	return doctormale_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table doctor
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    public void setDoctormale_Indicator(int doctormale_Indicator) {
	this.doctormale_Indicator = doctormale_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table doctor
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    public int getBirthday_Indicator() {
	return birthday_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table doctor
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    public void setBirthday_Indicator(int birthday_Indicator) {
	this.birthday_Indicator = birthday_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table doctor
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    public int getMobilephone_Indicator() {
	return mobilephone_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table doctor
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    public void setMobilephone_Indicator(int mobilephone_Indicator) {
	this.mobilephone_Indicator = mobilephone_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table doctor
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    public int getContactphone_Indicator() {
	return contactphone_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table doctor
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    public void setContactphone_Indicator(int contactphone_Indicator) {
	this.contactphone_Indicator = contactphone_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table doctor
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    public int getLevel_Indicator() {
	return level_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table doctor
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    public void setLevel_Indicator(int level_Indicator) {
	this.level_Indicator = level_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table doctor
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    public int getMajardesc_Indicator() {
	return majardesc_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table doctor
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    public void setMajardesc_Indicator(int majardesc_Indicator) {
	this.majardesc_Indicator = majardesc_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table doctor
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    public int getCurrentlogintime_Indicator() {
	return currentlogintime_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table doctor
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    public void setCurrentlogintime_Indicator(int currentlogintime_Indicator) {
	this.currentlogintime_Indicator = currentlogintime_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table doctor
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    public int getLatestlogintime_Indicator() {
	return latestlogintime_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table doctor
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    public void setLatestlogintime_Indicator(int latestlogintime_Indicator) {
	this.latestlogintime_Indicator = latestlogintime_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table doctor
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    public int getCreateuser_Indicator() {
	return createuser_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table doctor
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    public void setCreateuser_Indicator(int createuser_Indicator) {
	this.createuser_Indicator = createuser_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table doctor
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    public int getCreatetime_Indicator() {
	return createtime_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table doctor
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    public void setCreatetime_Indicator(int createtime_Indicator) {
	this.createtime_Indicator = createtime_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table doctor
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    public int getUpdateuser_Indicator() {
	return updateuser_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table doctor
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    public void setUpdateuser_Indicator(int updateuser_Indicator) {
	this.updateuser_Indicator = updateuser_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table doctor
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    public int getUpdatetime_Indicator() {
	return updatetime_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table doctor
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    public void setUpdatetime_Indicator(int updatetime_Indicator) {
	this.updatetime_Indicator = updatetime_Indicator;
    }
}