package com.micro.web.entities;

public class EssayExample extends Essay {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table essay
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public static final int EXAMPLE_IGNORE = 0;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table essay
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public static final int EXAMPLE_NULL = 1;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table essay
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public static final int EXAMPLE_NOT_NULL = 2;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table essay
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public static final int EXAMPLE_EQUALS = 3;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table essay
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public static final int EXAMPLE_NOT_EQUALS = 4;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table essay
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public static final int EXAMPLE_GREATER_THAN = 5;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table essay
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public static final int EXAMPLE_GREATER_THAN_OR_EQUAL = 6;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table essay
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public static final int EXAMPLE_LESS_THAN = 7;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table essay
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public static final int EXAMPLE_LESS_THAN_OR_EQUAL = 8;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table essay
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public static final int EXAMPLE_LIKE = 9;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table essay
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    private boolean combineTypeOr;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table essay
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    private int essayid_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table essay
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    private int tittle_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table essay
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    private int visitTimes_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table essay
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    private int reputationGood_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table essay
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    private int reputationBad_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table essay
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    private int picture_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table essay
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    private int path_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table essay
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    private int registertime_Indicator;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table essay
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public void setCombineTypeOr(boolean combineTypeOr) {
        this.combineTypeOr = combineTypeOr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table essay
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public boolean isCombineTypeOr() {
        return combineTypeOr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table essay
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public int getEssayid_Indicator() {
        return essayid_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table essay
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public void setEssayid_Indicator(int essayid_Indicator) {
        this.essayid_Indicator = essayid_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table essay
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public int getTittle_Indicator() {
        return tittle_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table essay
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public void setTittle_Indicator(int tittle_Indicator) {
        this.tittle_Indicator = tittle_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table essay
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public int getVisitTimes_Indicator() {
        return visitTimes_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table essay
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public void setVisitTimes_Indicator(int visitTimes_Indicator) {
        this.visitTimes_Indicator = visitTimes_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table essay
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public int getReputationGood_Indicator() {
        return reputationGood_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table essay
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public void setReputationGood_Indicator(int reputationGood_Indicator) {
        this.reputationGood_Indicator = reputationGood_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table essay
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public int getReputationBad_Indicator() {
        return reputationBad_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table essay
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public void setReputationBad_Indicator(int reputationBad_Indicator) {
        this.reputationBad_Indicator = reputationBad_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table essay
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public int getPicture_Indicator() {
        return picture_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table essay
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public void setPicture_Indicator(int picture_Indicator) {
        this.picture_Indicator = picture_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table essay
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public int getPath_Indicator() {
        return path_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table essay
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public void setPath_Indicator(int path_Indicator) {
        this.path_Indicator = path_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table essay
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public int getRegistertime_Indicator() {
        return registertime_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table essay
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public void setRegistertime_Indicator(int registertime_Indicator) {
        this.registertime_Indicator = registertime_Indicator;
    }
}