package com.micro.web.entities;

public class EssaycommentsExample extends Essaycomments {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table essaycomments
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public static final int EXAMPLE_IGNORE = 0;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table essaycomments
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public static final int EXAMPLE_NULL = 1;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table essaycomments
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public static final int EXAMPLE_NOT_NULL = 2;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table essaycomments
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public static final int EXAMPLE_EQUALS = 3;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table essaycomments
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public static final int EXAMPLE_NOT_EQUALS = 4;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table essaycomments
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public static final int EXAMPLE_GREATER_THAN = 5;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table essaycomments
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public static final int EXAMPLE_GREATER_THAN_OR_EQUAL = 6;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table essaycomments
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public static final int EXAMPLE_LESS_THAN = 7;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table essaycomments
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public static final int EXAMPLE_LESS_THAN_OR_EQUAL = 8;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table essaycomments
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public static final int EXAMPLE_LIKE = 9;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table essaycomments
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    private boolean combineTypeOr;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table essaycomments
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    private int essaycommentsid_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table essaycomments
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    private int userid_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table essaycomments
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    private int essaycommentsEssayid_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table essaycomments
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    private int essaycommentsUserid_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table essaycomments
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    private int content_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table essaycomments
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    private int registertime_Indicator;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table essaycomments
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public void setCombineTypeOr(boolean combineTypeOr) {
        this.combineTypeOr = combineTypeOr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table essaycomments
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public boolean isCombineTypeOr() {
        return combineTypeOr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table essaycomments
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public int getEssaycommentsid_Indicator() {
        return essaycommentsid_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table essaycomments
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public void setEssaycommentsid_Indicator(int essaycommentsid_Indicator) {
        this.essaycommentsid_Indicator = essaycommentsid_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table essaycomments
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public int getUserid_Indicator() {
        return userid_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table essaycomments
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public void setUserid_Indicator(int userid_Indicator) {
        this.userid_Indicator = userid_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table essaycomments
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public int getEssaycommentsEssayid_Indicator() {
        return essaycommentsEssayid_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table essaycomments
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public void setEssaycommentsEssayid_Indicator(int essaycommentsEssayid_Indicator) {
        this.essaycommentsEssayid_Indicator = essaycommentsEssayid_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table essaycomments
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public int getEssaycommentsUserid_Indicator() {
        return essaycommentsUserid_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table essaycomments
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public void setEssaycommentsUserid_Indicator(int essaycommentsUserid_Indicator) {
        this.essaycommentsUserid_Indicator = essaycommentsUserid_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table essaycomments
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public int getContent_Indicator() {
        return content_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table essaycomments
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public void setContent_Indicator(int content_Indicator) {
        this.content_Indicator = content_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table essaycomments
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public int getRegistertime_Indicator() {
        return registertime_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table essaycomments
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public void setRegistertime_Indicator(int registertime_Indicator) {
        this.registertime_Indicator = registertime_Indicator;
    }
}