package com.micro.web.entities;

import java.util.Date;

public class Essay {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column essay.essayId
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    private String essayid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column essay.tittle
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    private String tittle;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column essay.visit_times
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    private Integer visitTimes;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column essay.reputation_good
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    private Integer reputationGood;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column essay.reputation_bad
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    private Integer reputationBad;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column essay.picture
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    private String picture;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column essay.path
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    private String path;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column essay.registerTime
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    private Date registertime;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column essay.essayId
     *
     * @return the value of essay.essayId
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public String getEssayid() {
        return essayid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column essay.essayId
     *
     * @param essayid the value for essay.essayId
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public void setEssayid(String essayid) {
        this.essayid = essayid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column essay.tittle
     *
     * @return the value of essay.tittle
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public String getTittle() {
        return tittle;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column essay.tittle
     *
     * @param tittle the value for essay.tittle
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public void setTittle(String tittle) {
        this.tittle = tittle;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column essay.visit_times
     *
     * @return the value of essay.visit_times
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public Integer getVisitTimes() {
        return visitTimes;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column essay.visit_times
     *
     * @param visitTimes the value for essay.visit_times
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public void setVisitTimes(Integer visitTimes) {
        this.visitTimes = visitTimes;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column essay.reputation_good
     *
     * @return the value of essay.reputation_good
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public Integer getReputationGood() {
        return reputationGood;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column essay.reputation_good
     *
     * @param reputationGood the value for essay.reputation_good
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public void setReputationGood(Integer reputationGood) {
        this.reputationGood = reputationGood;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column essay.reputation_bad
     *
     * @return the value of essay.reputation_bad
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public Integer getReputationBad() {
        return reputationBad;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column essay.reputation_bad
     *
     * @param reputationBad the value for essay.reputation_bad
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public void setReputationBad(Integer reputationBad) {
        this.reputationBad = reputationBad;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column essay.picture
     *
     * @return the value of essay.picture
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public String getPicture() {
        return picture;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column essay.picture
     *
     * @param picture the value for essay.picture
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public void setPicture(String picture) {
        this.picture = picture;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column essay.path
     *
     * @return the value of essay.path
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column essay.path
     *
     * @param path the value for essay.path
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public void setPath(String path) {
        this.path = path;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column essay.registerTime
     *
     * @return the value of essay.registerTime
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public Date getRegistertime() {
        return registertime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column essay.registerTime
     *
     * @param registertime the value for essay.registerTime
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public void setRegistertime(Date registertime) {
        this.registertime = registertime;
    }
}