package com.micro.web.entities;

import java.util.Date;

public class Essaycomments {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column essaycomments.essayCommentsId
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    private String essaycommentsid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column essaycomments.userId
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    private String userid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column essaycomments.essayComments_essayId
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    private String essaycommentsEssayid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column essaycomments.essayComments_userId
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    private String essaycommentsUserid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column essaycomments.content
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    private String content;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column essaycomments.registerTime
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    private Date registertime;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column essaycomments.essayCommentsId
     *
     * @return the value of essaycomments.essayCommentsId
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public String getEssaycommentsid() {
        return essaycommentsid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column essaycomments.essayCommentsId
     *
     * @param essaycommentsid the value for essaycomments.essayCommentsId
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public void setEssaycommentsid(String essaycommentsid) {
        this.essaycommentsid = essaycommentsid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column essaycomments.userId
     *
     * @return the value of essaycomments.userId
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column essaycomments.userId
     *
     * @param userid the value for essaycomments.userId
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column essaycomments.essayComments_essayId
     *
     * @return the value of essaycomments.essayComments_essayId
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public String getEssaycommentsEssayid() {
        return essaycommentsEssayid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column essaycomments.essayComments_essayId
     *
     * @param essaycommentsEssayid the value for essaycomments.essayComments_essayId
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public void setEssaycommentsEssayid(String essaycommentsEssayid) {
        this.essaycommentsEssayid = essaycommentsEssayid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column essaycomments.essayComments_userId
     *
     * @return the value of essaycomments.essayComments_userId
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public String getEssaycommentsUserid() {
        return essaycommentsUserid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column essaycomments.essayComments_userId
     *
     * @param essaycommentsUserid the value for essaycomments.essayComments_userId
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public void setEssaycommentsUserid(String essaycommentsUserid) {
        this.essaycommentsUserid = essaycommentsUserid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column essaycomments.content
     *
     * @return the value of essaycomments.content
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column essaycomments.content
     *
     * @param content the value for essaycomments.content
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column essaycomments.registerTime
     *
     * @return the value of essaycomments.registerTime
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public Date getRegistertime() {
        return registertime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column essaycomments.registerTime
     *
     * @param registertime the value for essaycomments.registerTime
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public void setRegistertime(Date registertime) {
        this.registertime = registertime;
    }
}