package com.micro.web.entities;

import java.util.Date;

public class User {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column user.userId
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    private String userid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column user.phone
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    private Integer phone;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column user.name
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    private String name;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column user.authority
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    private Integer authority;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column user.username
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    private String username;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column user.password
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    private String password;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column user.idcard
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    private String idcard;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column user.registerTime
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    private Date registertime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column user.lastLogin
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    private Date lastlogin;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column user.userId
     *
     * @return the value of user.userId
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column user.userId
     *
     * @param userid the value for user.userId
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column user.phone
     *
     * @return the value of user.phone
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public Integer getPhone() {
        return phone;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column user.phone
     *
     * @param phone the value for user.phone
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public void setPhone(Integer phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column user.name
     *
     * @return the value of user.name
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column user.name
     *
     * @param name the value for user.name
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column user.authority
     *
     * @return the value of user.authority
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public Integer getAuthority() {
        return authority;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column user.authority
     *
     * @param authority the value for user.authority
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public void setAuthority(Integer authority) {
        this.authority = authority;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column user.username
     *
     * @return the value of user.username
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column user.username
     *
     * @param username the value for user.username
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column user.idcard
     *
     * @return the value of user.idcard
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public String getIdcard() {
        return idcard;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column user.idcard
     *
     * @param idcard the value for user.idcard
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public void setIdcard(String idcard) {
        this.idcard = idcard;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column user.registerTime
     *
     * @return the value of user.registerTime
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public Date getRegistertime() {
        return registertime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column user.registerTime
     *
     * @param registertime the value for user.registerTime
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public void setRegistertime(Date registertime) {
        this.registertime = registertime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column user.lastLogin
     *
     * @return the value of user.lastLogin
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public Date getLastlogin() {
        return lastlogin;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column user.lastLogin
     *
     * @param lastlogin the value for user.lastLogin
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public void setLastlogin(Date lastlogin) {
        this.lastlogin = lastlogin;
    }
}