package com.micro.web.entities;

public class UserExample extends User {

    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table user
     * @abatorgenerated  Fri Dec 20 11:10:55 CST 2013
     */
    public static final int EXAMPLE_IGNORE = 0;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table user
     * @abatorgenerated  Fri Dec 20 11:10:55 CST 2013
     */
    public static final int EXAMPLE_NULL = 1;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table user
     * @abatorgenerated  Fri Dec 20 11:10:55 CST 2013
     */
    public static final int EXAMPLE_NOT_NULL = 2;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table user
     * @abatorgenerated  Fri Dec 20 11:10:55 CST 2013
     */
    public static final int EXAMPLE_EQUALS = 3;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table user
     * @abatorgenerated  Fri Dec 20 11:10:55 CST 2013
     */
    public static final int EXAMPLE_NOT_EQUALS = 4;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table user
     * @abatorgenerated  Fri Dec 20 11:10:55 CST 2013
     */
    public static final int EXAMPLE_GREATER_THAN = 5;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table user
     * @abatorgenerated  Fri Dec 20 11:10:55 CST 2013
     */
    public static final int EXAMPLE_GREATER_THAN_OR_EQUAL = 6;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table user
     * @abatorgenerated  Fri Dec 20 11:10:55 CST 2013
     */
    public static final int EXAMPLE_LESS_THAN = 7;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table user
     * @abatorgenerated  Fri Dec 20 11:10:55 CST 2013
     */
    public static final int EXAMPLE_LESS_THAN_OR_EQUAL = 8;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table user
     * @abatorgenerated  Fri Dec 20 11:10:55 CST 2013
     */
    public static final int EXAMPLE_LIKE = 9;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table user
     * @abatorgenerated  Fri Dec 20 11:10:55 CST 2013
     */
    private boolean combineTypeOr;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table user
     * @abatorgenerated  Fri Dec 20 11:10:55 CST 2013
     */
    private int userid_Indicator;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table user
     * @abatorgenerated  Fri Dec 20 11:10:55 CST 2013
     */
    private int username_Indicator;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table user
     * @abatorgenerated  Fri Dec 20 11:10:55 CST 2013
     */
    private int password_Indicator;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table user
     * @abatorgenerated  Fri Dec 20 11:10:55 CST 2013
     */
    private int email_Indicator;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table user
     * @abatorgenerated  Fri Dec 20 11:10:55 CST 2013
     */
    private int usertype_Indicator;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table user
     * @abatorgenerated  Fri Dec 20 11:10:55 CST 2013
     */
    private int phone_Indicator;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table user
     * @abatorgenerated  Fri Dec 20 11:10:55 CST 2013
     */
    private int insertTime_Indicator;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table user
     * @abatorgenerated  Fri Dec 20 11:10:55 CST 2013
     */
    private int updateTime_Indicator;

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table user
     * @abatorgenerated  Fri Dec 20 11:10:55 CST 2013
     */
    public void setCombineTypeOr(boolean combineTypeOr) {
	this.combineTypeOr = combineTypeOr;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table user
     * @abatorgenerated  Fri Dec 20 11:10:55 CST 2013
     */
    public boolean isCombineTypeOr() {
	return combineTypeOr;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table user
     * @abatorgenerated  Fri Dec 20 11:10:55 CST 2013
     */
    public int getUserid_Indicator() {
	return userid_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table user
     * @abatorgenerated  Fri Dec 20 11:10:55 CST 2013
     */
    public void setUserid_Indicator(int userid_Indicator) {
	this.userid_Indicator = userid_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table user
     * @abatorgenerated  Fri Dec 20 11:10:55 CST 2013
     */
    public int getUsername_Indicator() {
	return username_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table user
     * @abatorgenerated  Fri Dec 20 11:10:55 CST 2013
     */
    public void setUsername_Indicator(int username_Indicator) {
	this.username_Indicator = username_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table user
     * @abatorgenerated  Fri Dec 20 11:10:55 CST 2013
     */
    public int getPassword_Indicator() {
	return password_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table user
     * @abatorgenerated  Fri Dec 20 11:10:55 CST 2013
     */
    public void setPassword_Indicator(int password_Indicator) {
	this.password_Indicator = password_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table user
     * @abatorgenerated  Fri Dec 20 11:10:55 CST 2013
     */
    public int getEmail_Indicator() {
	return email_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table user
     * @abatorgenerated  Fri Dec 20 11:10:55 CST 2013
     */
    public void setEmail_Indicator(int email_Indicator) {
	this.email_Indicator = email_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table user
     * @abatorgenerated  Fri Dec 20 11:10:55 CST 2013
     */
    public int getUsertype_Indicator() {
	return usertype_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table user
     * @abatorgenerated  Fri Dec 20 11:10:55 CST 2013
     */
    public void setUsertype_Indicator(int usertype_Indicator) {
	this.usertype_Indicator = usertype_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table user
     * @abatorgenerated  Fri Dec 20 11:10:55 CST 2013
     */
    public int getPhone_Indicator() {
	return phone_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table user
     * @abatorgenerated  Fri Dec 20 11:10:55 CST 2013
     */
    public void setPhone_Indicator(int phone_Indicator) {
	this.phone_Indicator = phone_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table user
     * @abatorgenerated  Fri Dec 20 11:10:55 CST 2013
     */
    public int getInsertTime_Indicator() {
	return insertTime_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table user
     * @abatorgenerated  Fri Dec 20 11:10:55 CST 2013
     */
    public void setInsertTime_Indicator(int insertTime_Indicator) {
	this.insertTime_Indicator = insertTime_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table user
     * @abatorgenerated  Fri Dec 20 11:10:55 CST 2013
     */
    public int getUpdateTime_Indicator() {
	return updateTime_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table user
     * @abatorgenerated  Fri Dec 20 11:10:55 CST 2013
     */
    public void setUpdateTime_Indicator(int updateTime_Indicator) {
	this.updateTime_Indicator = updateTime_Indicator;
    }
}