package com.micro.web.entities;

import java.util.Date;

public class User {

    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column user.userid
     * @abatorgenerated  Thu Dec 19 13:46:17 CST 2013
     */
    private Long userid;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column user.username
     * @abatorgenerated  Thu Dec 19 13:46:17 CST 2013
     */
    private String username;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column user.password
     * @abatorgenerated  Thu Dec 19 13:46:17 CST 2013
     */
    private String password;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column user.email
     * @abatorgenerated  Thu Dec 19 13:46:17 CST 2013
     */
    private String email;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column user.phone
     * @abatorgenerated  Thu Dec 19 13:46:17 CST 2013
     */
    private String phone;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column user.insert_time
     * @abatorgenerated  Thu Dec 19 13:46:17 CST 2013
     */
    private Date insertTime;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column user.update_time
     * @abatorgenerated  Thu Dec 19 13:46:17 CST 2013
     */
    private Date updateTime;

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column user.userid
     * @return  the value of user.userid
     * @abatorgenerated  Thu Dec 19 13:46:17 CST 2013
     */
    public Long getUserid() {
	return userid;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column user.userid
     * @param userid  the value for user.userid
     * @abatorgenerated  Thu Dec 19 13:46:17 CST 2013
     */
    public void setUserid(Long userid) {
	this.userid = userid;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column user.username
     * @return  the value of user.username
     * @abatorgenerated  Thu Dec 19 13:46:17 CST 2013
     */
    public String getUsername() {
	return username;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column user.username
     * @param username  the value for user.username
     * @abatorgenerated  Thu Dec 19 13:46:17 CST 2013
     */
    public void setUsername(String username) {
	this.username = username;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column user.password
     * @return  the value of user.password
     * @abatorgenerated  Thu Dec 19 13:46:17 CST 2013
     */
    public String getPassword() {
	return password;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column user.password
     * @param password  the value for user.password
     * @abatorgenerated  Thu Dec 19 13:46:17 CST 2013
     */
    public void setPassword(String password) {
	this.password = password;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column user.email
     * @return  the value of user.email
     * @abatorgenerated  Thu Dec 19 13:46:17 CST 2013
     */
    public String getEmail() {
	return email;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column user.email
     * @param email  the value for user.email
     * @abatorgenerated  Thu Dec 19 13:46:17 CST 2013
     */
    public void setEmail(String email) {
	this.email = email;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column user.phone
     * @return  the value of user.phone
     * @abatorgenerated  Thu Dec 19 13:46:17 CST 2013
     */
    public String getPhone() {
	return phone;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column user.phone
     * @param phone  the value for user.phone
     * @abatorgenerated  Thu Dec 19 13:46:17 CST 2013
     */
    public void setPhone(String phone) {
	this.phone = phone;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column user.insert_time
     * @return  the value of user.insert_time
     * @abatorgenerated  Thu Dec 19 13:46:17 CST 2013
     */
    public Date getInsertTime() {
	return insertTime;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column user.insert_time
     * @param insertTime  the value for user.insert_time
     * @abatorgenerated  Thu Dec 19 13:46:17 CST 2013
     */
    public void setInsertTime(Date insertTime) {
	this.insertTime = insertTime;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column user.update_time
     * @return  the value of user.update_time
     * @abatorgenerated  Thu Dec 19 13:46:17 CST 2013
     */
    public Date getUpdateTime() {
	return updateTime;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column user.update_time
     * @param updateTime  the value for user.update_time
     * @abatorgenerated  Thu Dec 19 13:46:17 CST 2013
     */
    public void setUpdateTime(Date updateTime) {
	this.updateTime = updateTime;
    }
}