package com.micro.web.entities;

public class UserExample extends User {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table user
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public static final int EXAMPLE_IGNORE = 0;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table user
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public static final int EXAMPLE_NULL = 1;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table user
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public static final int EXAMPLE_NOT_NULL = 2;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table user
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public static final int EXAMPLE_EQUALS = 3;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table user
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public static final int EXAMPLE_NOT_EQUALS = 4;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table user
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public static final int EXAMPLE_GREATER_THAN = 5;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table user
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public static final int EXAMPLE_GREATER_THAN_OR_EQUAL = 6;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table user
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public static final int EXAMPLE_LESS_THAN = 7;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table user
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public static final int EXAMPLE_LESS_THAN_OR_EQUAL = 8;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table user
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public static final int EXAMPLE_LIKE = 9;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table user
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    private boolean combineTypeOr;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table user
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    private int userid_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table user
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    private int phone_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table user
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    private int name_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table user
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    private int authority_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table user
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    private int username_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table user
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    private int password_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table user
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    private int idcard_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table user
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    private int registertime_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table user
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    private int lastlogin_Indicator;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public void setCombineTypeOr(boolean combineTypeOr) {
        this.combineTypeOr = combineTypeOr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public boolean isCombineTypeOr() {
        return combineTypeOr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public int getUserid_Indicator() {
        return userid_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public void setUserid_Indicator(int userid_Indicator) {
        this.userid_Indicator = userid_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public int getPhone_Indicator() {
        return phone_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public void setPhone_Indicator(int phone_Indicator) {
        this.phone_Indicator = phone_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public int getName_Indicator() {
        return name_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public void setName_Indicator(int name_Indicator) {
        this.name_Indicator = name_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public int getAuthority_Indicator() {
        return authority_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public void setAuthority_Indicator(int authority_Indicator) {
        this.authority_Indicator = authority_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public int getUsername_Indicator() {
        return username_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public void setUsername_Indicator(int username_Indicator) {
        this.username_Indicator = username_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public int getPassword_Indicator() {
        return password_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public void setPassword_Indicator(int password_Indicator) {
        this.password_Indicator = password_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public int getIdcard_Indicator() {
        return idcard_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public void setIdcard_Indicator(int idcard_Indicator) {
        this.idcard_Indicator = idcard_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public int getRegistertime_Indicator() {
        return registertime_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public void setRegistertime_Indicator(int registertime_Indicator) {
        this.registertime_Indicator = registertime_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public int getLastlogin_Indicator() {
        return lastlogin_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public void setLastlogin_Indicator(int lastlogin_Indicator) {
        this.lastlogin_Indicator = lastlogin_Indicator;
    }
}