package com.micro.web.entities;

import java.util.Date;

public class Videocomments {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column videocomments.videoCommentsId
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    private String videocommentsid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column videocomments.videoId
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    private String videoid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column videocomments.userId
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    private String userid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column videocomments.videoComments_videoId
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    private String videocommentsVideoid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column videocomments.videoComments_userId
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    private String videocommentsUserid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column videocomments.content
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    private String content;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column videocomments.registerTime
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    private Date registertime;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column videocomments.videoCommentsId
     *
     * @return the value of videocomments.videoCommentsId
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public String getVideocommentsid() {
        return videocommentsid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column videocomments.videoCommentsId
     *
     * @param videocommentsid the value for videocomments.videoCommentsId
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public void setVideocommentsid(String videocommentsid) {
        this.videocommentsid = videocommentsid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column videocomments.videoId
     *
     * @return the value of videocomments.videoId
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public String getVideoid() {
        return videoid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column videocomments.videoId
     *
     * @param videoid the value for videocomments.videoId
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public void setVideoid(String videoid) {
        this.videoid = videoid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column videocomments.userId
     *
     * @return the value of videocomments.userId
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column videocomments.userId
     *
     * @param userid the value for videocomments.userId
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column videocomments.videoComments_videoId
     *
     * @return the value of videocomments.videoComments_videoId
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public String getVideocommentsVideoid() {
        return videocommentsVideoid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column videocomments.videoComments_videoId
     *
     * @param videocommentsVideoid the value for videocomments.videoComments_videoId
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public void setVideocommentsVideoid(String videocommentsVideoid) {
        this.videocommentsVideoid = videocommentsVideoid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column videocomments.videoComments_userId
     *
     * @return the value of videocomments.videoComments_userId
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public String getVideocommentsUserid() {
        return videocommentsUserid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column videocomments.videoComments_userId
     *
     * @param videocommentsUserid the value for videocomments.videoComments_userId
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public void setVideocommentsUserid(String videocommentsUserid) {
        this.videocommentsUserid = videocommentsUserid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column videocomments.content
     *
     * @return the value of videocomments.content
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column videocomments.content
     *
     * @param content the value for videocomments.content
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column videocomments.registerTime
     *
     * @return the value of videocomments.registerTime
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public Date getRegistertime() {
        return registertime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column videocomments.registerTime
     *
     * @param registertime the value for videocomments.registerTime
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    public void setRegistertime(Date registertime) {
        this.registertime = registertime;
    }
}