package com.micro.web.dao;

import java.util.List;

import com.micro.web.dto.BaseResultDto;
import com.micro.web.dto.DoctorSearchDto;
import com.micro.web.entities.Doctor;
import com.micro.web.entities.DoctorExample;


public interface DoctorDAO {
    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table doctor
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    void insert(Doctor record);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table doctor
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    int updateByPrimaryKey(Doctor record);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table doctor
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    int updateByPrimaryKeySelective(Doctor record);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table doctor
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    List selectByExample(DoctorExample example, String orderByClause);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table doctor
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    List selectByExample(DoctorExample example);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table doctor
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    Doctor selectByPrimaryKey(Long doctorid);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table doctor
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    int deleteByExample(DoctorExample example);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table doctor
     * @abatorgenerated  Sun Mar 10 20:47:14 CST 2013
     */
    int deleteByPrimaryKey(Long doctorid);

    /**
     * Search doctors.
     * @param sercharDto
     * @return
     */
    public BaseResultDto<Doctor> selectBySearchDto(DoctorSearchDto sercharDto);
    
    /**
     * xumeng
     */
    Doctor findDoctorByLoginnameAndPassword(Doctor doctor);
}