package com.micro.web.dao;

import com.micro.web.entities.Essaycomments;
import com.micro.web.entities.EssaycommentsExample;
import java.util.List;

public interface EssaycommentsDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table essaycomments
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    void insert(Essaycomments record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table essaycomments
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    int updateByPrimaryKey(Essaycomments record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table essaycomments
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    int updateByPrimaryKeySelective(Essaycomments record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table essaycomments
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    List selectByExample(EssaycommentsExample example, String orderByClause);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table essaycomments
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    List selectByExample(EssaycommentsExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table essaycomments
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    Essaycomments selectByPrimaryKey(String essaycommentsid);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table essaycomments
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    int deleteByExample(EssaycommentsExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table essaycomments
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    int deleteByPrimaryKey(String essaycommentsid);
}