package com.micro.web.dao;

import com.micro.web.entities.User;
import com.micro.web.entities.UserExample;

import java.util.List;

public interface UserDAO {

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table user
     * @abatorgenerated  Fri Dec 20 11:10:55 CST 2013
     */
    void insert(User record);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table user
     * @abatorgenerated  Fri Dec 20 11:10:55 CST 2013
     */
    int updateByPrimaryKey(User record);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table user
     * @abatorgenerated  Fri Dec 20 11:10:55 CST 2013
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table user
     * @abatorgenerated  Fri Dec 20 11:10:55 CST 2013
     */
    List selectByExample(UserExample example, String orderByClause);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table user
     * @abatorgenerated  Fri Dec 20 11:10:55 CST 2013
     */
    List selectByExample(UserExample example);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table user
     * @abatorgenerated  Fri Dec 20 11:10:55 CST 2013
     */
    User selectByPrimaryKey(Long userid);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table user
     * @abatorgenerated  Fri Dec 20 11:10:55 CST 2013
     */
    int deleteByExample(UserExample example);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table user
     * @abatorgenerated  Fri Dec 20 11:10:55 CST 2013
     */
    int deleteByPrimaryKey(Long userid);

	User selectByUserName(String username, String password);
}