package com.micro.web.dao;

import com.micro.web.entities.Videocomments;
import com.micro.web.entities.VideocommentsExample;
import java.util.List;

public interface VideocommentsDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table videocomments
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    void insert(Videocomments record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table videocomments
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    int updateByPrimaryKey(Videocomments record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table videocomments
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    int updateByPrimaryKeySelective(Videocomments record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table videocomments
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    List selectByExample(VideocommentsExample example, String orderByClause);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table videocomments
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    List selectByExample(VideocommentsExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table videocomments
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    Videocomments selectByPrimaryKey(String videocommentsid);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table videocomments
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    int deleteByExample(VideocommentsExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table videocomments
     *
     * @abatorgenerated Sun Mar 24 18:16:18 CST 2013
     */
    int deleteByPrimaryKey(String videocommentsid);
}